/**
 * Generated by tsnapi — public API snapshot of `@yunzhen/starter-ts`
 */
// #region Variables
export declare const one: number;
export declare const two: number;
// #endregion

// #region Other
export { throttle }
// #endregion